const IDENTIFIER = '@@player/';

export const FETCH_SONGS_REQUEST = `${IDENTIFIER}FETCH_SONGS_REQUEST`;
export const FETCH_SONGS_FAILURE = `${IDENTIFIER}FETCH_SONGS_FAILURE`;
export const FETCH_SONGS_SUCCESS = `${IDENTIFIER}FETCH_SONGS_SUCCESS`;


export const PLAY = `${IDENTIFIER}PLAY`;
export const PAUSE = `${IDENTIFIER}PAUSE`;
export const SET_CURRENT_TRACK = `${IDENTIFIER}SET_CURRENT_TRACK`;
export const TOGGLE_REPEAT = `${IDENTIFIER}TOGGLE_REPEAT`;
export const TOGGLE_MUTE = `${IDENTIFIER}TOGGLE_MUTE`;
export const TOGGLE_RANDOM = `${IDENTIFIER}TOGGLE_RANDOM`;
export const SET_PROGRESS = `${IDENTIFIER}SET_PROGRESS`;
export const CHANGE_THEME = `${IDENTIFIER}CHANGE_THEME`;



