const IDENTIFIER = '@@player/';

export const FETCH_AUTH_REQUEST = `${IDENTIFIER}FETCH_AUTH_REQUEST`;
export const FETCH_AUTH_FAILURE = `${IDENTIFIER}FETCH_AUTH_FAILURE`;
export const FETCH_AUTH_SUCCESS = `${IDENTIFIER}FETCH_AUTH_SUCCESS`;

export const FETCH_AUTH_TOKEN_REQUEST = `${IDENTIFIER}FETCH_AUTH_TOKEN_REQUEST`;
export const FETCH_AUTH_TOKEN_FAILURE = `${IDENTIFIER}FETCH_AUTH_TOKEN_FAILURE`;
export const FETCH_AUTH_TOKEN_SUCCESS = `${IDENTIFIER}FETCH_AUTH_TOKEN_SUCCESS`;






