const IDENTIFIER = '@@player/';

export const FETCH_PLAYLIST_REQUEST = `${IDENTIFIER}FETCH_PLAYLIST__REQUEST`;
export const FETCH_PLAYLIST_FAILURE = `${IDENTIFIER}FETCH_PLAYLIST_FAILURE`;
export const FETCH_PLAYLIST_SUCCESS = `${IDENTIFIER}FETCH_PLAYLIST_SUCCESS`;

export const FETCH_SONGS_REQUEST = `${IDENTIFIER}FETCH_SONGS_REQUEST`;
export const FETCH_SONGS_FAILURE = `${IDENTIFIER}FETCH_SONGS_FAILURE`;
export const FETCH_SONGS_SUCCESS = `${IDENTIFIER}FETCH_SONGS_SUCCESS`;


export const PLAY = `${IDENTIFIER}PLAY`;
export const PAUSE = `${IDENTIFIER}PAUSE`;
export const SET_CURRENT_TRACK = `${IDENTIFIER}SET_CURRENT_TRACK`;
export const TOGGLE_REPEAT = `${IDENTIFIER}TOGGLE_REPEAT`;
export const TOGGLE_MUTE = `${IDENTIFIER}TOGGLE_MUTE`;
export const TOGGLE_RANDOM = `${IDENTIFIER}TOGGLE_RANDOM`;
export const TOGGLE_SEARCH = `${IDENTIFIER}TOGGLE_SEARCH`;
export const SET_PROGRESS = `${IDENTIFIER}SET_PROGRESS`;
export const CHANGE_THEME = `${IDENTIFIER}CHANGE_THEME`;

export const UPDATE_TRACKS = `${IDENTIFIER}DELETE_TRACK`;
export const UPDATE_SEARCH_TRACKS = `${IDENTIFIER}UPDATE_SEARCH_TRACKS`;
